### ISSUE TITLE
magic link - email text

### ISSUE THREAD

**Issue by giladvidal** [SAP/ownid-server-sdk-net#111]
The text should explain to the user that they have to open the link from the same browser they are using to access the application.

Mike - please help with the text.

SoW:

1. Update text
1. Create button
1. Test in different mailboxes: Outlook, Gmail, Apple Mail etc.

**Comment by mike-cast** [comment]
**Text**
Hi User,
 Use the link below to log in to your account. Make sure to use the same browser used to receive this email.

Your magic link to login

If the link above doesn’t work, try copy and pasting the following URL in the browser used to receive the email: https://www.LINK-HERE.com

**Design**
https://www.figma.com/file/dlZX0QHeDNFD1PQQNWmqNA/Skip-the-password?node-id=1187%3A181

**Screen**
![Screen Shot 2021-01-27 at 10.46.27 AM.png](https://images.zenhubusercontent.com/5ff6187d83f4aa0d523061e4/c25275f9-c7e9-4435-8e14-a0e860189be3)

**Comment by vospitannikov** [comment]
After discussion with Mike, the text changed from 
```
...
If you didn't request this password reset or you received this message in error, please disregard this email.
```
to 
```
...
If you didn’t make this magic link request, please disregard this email.
```
