### ISSUE TITLE
multi-tenant - Research - API Gateway

### ISSUE THREAD

**Issue by giladvidal** [SAP/ownid-server-sdk-net#130]
The gateway is a public API, receive requests, check authentication and pass to processing.

Receive requests:
- self-service application (Gigya authentication)
- client command line (key, secret)

Check authentication:
Currently either Gigya or key/secret but should be flexible to add additional methods

Pass to processing:
Once authenticated, the API can be processed

SoW:

1. API GW works with AWS API GW (UI) and K8S Ingress controller 
1. Working request forwarding to internal services

Some DOCS:
https://aws.amazon.com/blogs/containers/api-gateway-as-an-ingress-controller-for-eks/
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-use-lambda-authorizer.html

**Comment by bdonchenko** [comment]
![image.png](https://images.zenhubusercontent.com/5e8706d8b4859d575b76efb0/d6fe8e37-6cfe-480e-bcf4-57cf47fa94cf)
