### ISSUE TITLE
[Release] Infrartructure

### ISSUE THREAD

**Issue by vitalii-marynkevych** [SAP/ownid-server-sdk-net#150]
:white_check_mark:   -  when is done
<br>

| Change / Env 	| dev 	| staging 	| prod 	|
|--------------	|:---:	|:-------:	|:----:	|
| Gigya scheme ownId.connections.authType             	|   :white_check_mark:  	|       :white_check_mark:  	|    :white_check_mark:  	|
| Auth Lambda for Console App             	|   :white_check_mark:  	|       :white_check_mark:  	|  :white_check_mark:    	|
| Ingress for  Console App BE           	|   :white_check_mark:  	|       :white_check_mark:  	|      	|
| Api GW for Console App             	|   :white_check_mark:  	|       :white_check_mark:  	|      	|
| Create Console DB          	|   :white_check_mark:  	|       :white_check_mark:  	|      	|
| Console manifests            	|   :white_check_mark:  	|       :white_check_mark:  	|      	|
| Console k8s secrets            	|   :white_check_mark:  	|       :white_check_mark:  	|      	|
| Console git secrets            	|   :white_check_mark:  	|       :white_check_mark:  	|      	|
| Console deploy script            	|   :white_check_mark:  	|       :white_check_mark:  	|      	|

**Comment by bdonchenko** [comment]
After each release to PRODUCTION we have to make sure these websites work properly:

https://sap.sharepoint.com/:x:/r/teams/OwnID/_layouts/15/guestaccess.aspx?e=nlO67R&wdLOR=c4B3E1CD9-BE5D-F945-BF26-4BDDD210483D&share=EVfL9UWcHjFJvq20xQGrahYB-rr_XdQhiADqMTGtIyMrWg

What hast to be tested:

1. Registration
1. Login
1. FIDO fallback
1. Link
1. Link on Login
1. Recovery
1. Magic link (if it's implemented)
