### ISSUE TITLE
Elastic type

### ISSUE THREAD

**Issue by giladvidal** [SAP/ownid-server-sdk-net#62]
r5.large.elasticsearch to something less expensive.

**Comment by vitalii-marynkevych** [comment]
Changed dev to:
Instance type (data) t3.medium.elasticsearch. 
Number of nodes 1

Changed prod to:
Instance type (data) t3.medium.elasticsearch
Number of nodes 2
Instance type (master )t3.small.elasticsearch
Number of master instances 3
